games/urls.py
from django.urls import path

from .views import filter_games

app_name = "api/games"

urlpatterns = [
    path("", filter_games, name="filter_games"),
]

vr_club/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("s/", include("url_shortener.urls")),
    path("", include("vr_club_site.urls")),
    path("", include("allauth.urls")),
    path("api/games/", include("games.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vr_club_site/urls.py
from django.urls import path

from .views import (
    index_page,
    devices_page,
    get_available_slots_view,
    get_available_slots_for_month_view,
    get_price_day,
)
from games.views import games_page

app_name = "site"

urlpatterns = [
    path("", index_page, name="home"),
    path("games/", games_page, name="games"),
    path("devices/", devices_page, name="devices"),
    path(
        "api/get_available_slots/",
        get_available_slots_view,
        name="get_available_slots",
    ),
    path(
        "api/get_available_slots_for_month/",
        get_available_slots_for_month_view,
        name="get_available_slots_for_month",
    ),
    path(
        "api/get_price_day/",
        get_price_day,
        name="get_price_day",
    ),
]

vr_club_site/models.py
from datetime import date

from django.db import models

# Create your models here.

ACTUAL = "AL"
OUTDATED = "OD"


class BookingTime(models.Model):
    STATUS_CHOICES = (
        (ACTUAL, "Actual"),
        (OUTDATED, "Outdated"),
    )
    TIME_CHOICES = [
        (f"{hour}-{hour + 1}", f"{hour}.00-{hour + 1}.00") for hour in range(12, 22)
    ]

    time = models.CharField(max_length=5, choices=TIME_CHOICES, null=False)
    status = models.CharField(
        max_length=2, choices=STATUS_CHOICES, null=False, default=ACTUAL
    )
    date = models.DateField(default=date.today)

    def __str__(self):
        return "{0} | {1} | {2}".format(self.date, self.time, self.status)


class Booking(models.Model):
    id = models.BigAutoField(
        auto_created=True,
        primary_key=True,
        serialize=False,
        verbose_name="ID",
    )
    name = models.CharField(max_length=32, null=False, default="vrclub")
    email = models.EmailField(max_length=64, null=False, default="vrclub@gmail.com")
    phone_number = models.CharField(
        max_length=20, null=True, blank=True, default="+380000000000"
    )
    comment = models.CharField(max_length=256, null=True)
    people_count = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    time = models.ManyToManyField(BookingTime)

    def __str__(self):
        return "{0} | {1}".format(self.email, self.price)


class Settings(models.Model):
    VARIABLE_TYPES = (
        ("str", "String"),
        ("int", "Integer"),
        ("decimal", "Decimal"),
        ("bool", "Boolean"),
    )

    name = models.CharField(max_length=100, unique=True)
    variable_type = models.CharField(max_length=10, choices=VARIABLE_TYPES)
    value = models.TextField()

    def __str__(self):
        return f"{self.name}:{self.variable_type} = {self.value}"

vr_club_site/forms.py
from django import forms

from .models import BookingTime


class BookingForm(forms.Form):
    name = forms.CharField(
        max_length=32,
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    date = forms.DateField(
        required=True,
        input_formats=["%d-%m-%Y"],
        widget=forms.DateInput(
            format="%d-%m-%Y",
            attrs={
                "class": "form-control",
            },
        ),
    )
    email = forms.EmailField(
        required=True,
        max_length=64,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    phone_number = forms.CharField(
        max_length=20,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    people_count = forms.IntegerField(min_value=1)
    comment = forms.CharField(
        max_length=256,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=False,
    )
    slots = forms.MultipleChoiceField(
        choices=BookingTime.TIME_CHOICES,
        widget=forms.CheckboxSelectMultiple(),
        required=True,
    )

vr_club_site/views.py
from datetime import datetime

from django.shortcuts import redirect, render
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse

from .forms import BookingForm
from .models import BookingTime
from .utils import (
    get_available_slots,
    get_available_slots_for_month,
    get_session_seats,
    is_all_neighbors,
    has_invalid_slots,
    book_session,
    MAX_SESSION,
    get_price,
    get_weekend_price,
    get_weekday_price,
)


def get_available_slots_view(request):
    if request.method == "GET":
        selected_date = request.GET.get("date")
        available_slots = get_available_slots(selected_date)
        return JsonResponse({"available_slots": available_slots})


def get_available_slots_for_month_view(request):
    if request.method == "GET":
        year = request.GET.get("year")
        month = request.GET.get("month")
        available_slots = get_available_slots_for_month(year, month)
        return JsonResponse({"available_slots": available_slots})


def get_price_day(request):
    if request.method == "GET":
        selected_date = request.GET.get("date")
        date_obj = datetime.strptime(selected_date, "%Y-%m-%d")
        price = get_price(date_obj)
        return JsonResponse({"price": price})


def index_page(request):
    if request.method == "POST":
        form = BookingForm(request.POST)
        if not form.is_valid():
            messages.error(request, "Будь ласка, оберіть слот, перед відправкою!")
            return render_index_page(request)
        selected_date = form.cleaned_data["date"]
        _available_slots = get_available_slots(selected_date)
        slot_av_slots = {
            y[0]: x for y, x in zip(BookingTime.TIME_CHOICES, _available_slots)
        }
        slot_compatibility = {
            y[0]: index for index, y in enumerate(BookingTime.TIME_CHOICES)
        }
        slots = form.cleaned_data["slots"]

        if len(slots) > MAX_SESSION:
            messages.error(
                request, f"Максимальна кількість обраних сеансів: {MAX_SESSION}"
            )
            return render_index_page(request)

        if len(slots) > 1:
            _is_all_neighbors = is_all_neighbors(slot_compatibility, slots)

            if not _is_all_neighbors:
                messages.error(request, "Сеанси мають бути суміжними")
                return render_index_page(request)

        people_count = form.cleaned_data["people_count"]
        _has_invalid_slots = has_invalid_slots(
            request, people_count, slot_av_slots, slots
        )

        if not _has_invalid_slots:
            book_session(request, slots, form.cleaned_data)
            return redirect("site:home")

    return render_index_page(request)


def render_index_page(request):
    signup_url = reverse("account_signup")
    login_url = reverse("account_login")
    form = BookingForm()
    return render(
        request,
        "site/index.html",
        {
            "form": form,
            "signup_url": signup_url,
            "login_url": login_url,
            "weekday_price": get_weekday_price(),
            "weekend_price": get_weekend_price(),
        },
    )


def devices_page(request):
    signup_url = reverse("account_signup")
    login_url = reverse("account_login")
    return render(
        request,
        "site/devices.html",
        {
            "signup_url": signup_url,
            "login_url": login_url,
        },
    )

vr_club_site/templates/site/booking.html
<div id="popup" class="popup">
    {% load static %}
    <link rel="stylesheet" href="{% static 'site/style/booking.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <div class="popup-container">
        <svg onclick="closePopup()" id="closePopup" class="close" width="32" height="32" viewBox="0 0 32 32" fill="none"
            xmlns="http://www.w3.org/2000/svg">
            <path
                d="M8.53317 25.3334L6.6665 23.4667L14.1332 16L6.6665 8.53335L8.53317 6.66669L15.9998 14.1334L23.4665 6.66669L25.3332 8.53335L17.8665 16L25.3332 23.4667L23.4665 25.3334L15.9998 17.8667L8.53317 25.3334Z"
                fill="black"></path>
        </svg>
        <div class="title-popup">
            <div class="half-1">Оберіть зручний час для гри в клубі:</div>
            <div class="half-2">м. Славута, вул. Бла-бла, 32</div>
            <div class="booking-date">01-01-2023</div>
            <form id="bookingForm" method="post" style="margin-top: 24px;">
                {% csrf_token %}
                <div style="display: none;">
                    {{ form.date }}
                </div>
                <div class="form-group">
                    {% for slot in form.slots %}
                        <div class="form-check">
                            <label class="form-check-label">
                                {{ slot }}
                            </label>
                            <label class="av_slots"></label>
                        </div>
                    {% endfor %}
                </div>
                <div class="people-count-price">
                    <div class="people-count">Кількість осіб:</div>
                    <div class="people-count-2">
                        <div class="number-input">
                        <div onclick="this.parentNode.querySelector('input[type=number]').stepDown()"
                            style="margin-left:16px"></div>
                        <input class="quantity" min="1" name="people_count" value="1" type="number" required
                            id="id_people_count">
                        <div onclick="this.parentNode.querySelector('input[type=number]').stepUp()"
                            class="Two plus" style="margin-right:16px"></div>
                    </div>
                    <span class="total_cost" id="total_cost" style="margin-left: auto">0.00 грн</span>
                    </div>
                </div>
                <div class="info-form">
                    <div class="column">
                    <div class="input-container">
                        <label for="{{ form.name.id_for_label }}">
                            <div class="frame-23">
                                <span class="e1">Ваше ім’я</span>
                                <span class="e2">*</span>
                            </div>
                        </label>
                        {{ form.name }}
                    </div>
                    <div class="input-container">
                        <label for="{{ form.email.id_for_label }}">
                            <span class="e1">Електронна адреса</span>
                            <span class="e2">*</span>
                        </label>
                        {{ form.email }}
                    </div>
                    </div>
                    <div class="column">
                        <div class="input-container">
                            <label for="{{ form.phone_number.id_for_label }}">
                                <span class="e1">Номер телефону</span>
                            </label>
                            {{ form.phone_number }}
                        </div>
                        <div class="input-container">
                            <label for="{{ form.comment.id_for_label }}">
                                <span class="e1">Коментар</span>
                            </label>
                            {{ form.comment }}
                        </div>
                    </div>
                </div>
                <div class="btn-booking">
                    <button  id="bookingButton" class="main-btn-blue-pop">забронювати</button>
                </div>
            </form>
        </div>
    </div>
<script src="{% static 'site/js/booking.js' %}"></script>
</div>

vr_club_site/templates/site/calendar.html
{% load static %}
<link rel="stylesheet" href="{% static 'site/style/calendar.css' %}">
<section id="booking" style="height: auto;">
    <div class="booking">
        <span>
            <span class="span1">Забронюй</span>
            <span class="span2"> час гри прямо зараз!</span>
        </span>
    </div>
    <div class="flex-calendar">
        <div class="month-nav">
            <div id="prevMonth" class="button-m item1">
                <svg class="caret-left" width="32" height="32" viewBox="0 0 32 32" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path d="M22 6L12 16L22 26" stroke="#4FB4FE" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round"></path>
                </svg>
                <div id="prevMonthBtn" class="name-month"></div>
            </div>
            <div class="month" id="month"></div>
            <div id="nextMonth" class="button-m item3">
                <div id="nextMonthBtn" class="name-month"></div>
                <svg class="caret-right" width="32" height="32" viewBox="0 0 32 32" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <path d="M12 6L22 16L12 26" stroke="#4FB4FE" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round"></path>
                </svg>
            </div>
        </div>
        <div class="weekdays">
            <div>Пн</div>
            <div>Вт</div>
            <div>Ср</div>
            <div>Чт</div>
            <div>Пт</div>
            <div>Сб</div>
            <div>Нд</div>
        </div>
        <div class="days" id="days"></div>
    </div>
   {% include 'site/booking.html' %}
    <script src="{% static 'site/js/calendar.js' %}"></script>
</section>
<script>
function formatTime(date) {
    const year = date.getFullYear();
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const day = date.getDate().toString().padStart(2, '0');
    const hours = date.getHours().toString().padStart(2, '0');
    const minutes = date.getMinutes().toString().padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function getCurrentTimeUTC() {
    const currentTime = new Date();
    const utcOffset = 0;
    return new Date(currentTime.getTime() + utcOffset * 60 * 60 * 1000);
}

async function getAvailableSlots(date) {
    fetch(`{% url 'site:get_available_slots' %}?date=${date}`, {
        method: "GET",
        headers: {
            "X-Requested-With": "XMLHttpRequest",
        },
    })
        .then(response => response.json())
        .then(data => {
            const avSlotsLabels = document.getElementsByClassName('av_slots');
            const currentTimeUTC2 = getCurrentTimeUTC();
            const slots = document.querySelectorAll('.form-check-label');

            for (let i = 0; i < avSlotsLabels.length; i++) {
                const avSlotElement = avSlotsLabels[i];
                const newAvSlotValue = data.available_slots[i];

                const slot = slots[i];
                const slotText = slot.textContent.trim();
                const hourRegex = /(\d+\.\d+)/;
                const matches = slotText.match(hourRegex);

                if (matches) {
                    const hour = parseFloat(matches[1]);
                    const slotDate = new Date(date);
                    slotDate.setHours(hour, 0, 0, 0);

                    if (slotDate <= currentTimeUTC2) {
                        avSlotElement.textContent = "";
                    } else if (newAvSlotValue > 0) {
                        avSlotElement.textContent = `${newAvSlotValue} місця`;
                    } else {
                        avSlotElement.textContent = "";
                    }
                }
            }
            updateSlotAvailability();
        });
}
async function getAvailableSlotsMonth(currentYear, currentMonth) {
    currentMonth += 1
    fetch(`{% url 'site:get_available_slots_for_month' %}?year=${currentYear}&month=${currentMonth}`, {
        method: "GET",
        headers: {
            "X-Requested-With": "XMLHttpRequest",
        },
    })
        .then(response => response.json())
        .then(data => {
            data.available_slots.forEach(item => {
                const date = new Date(item.date);
                const dayNumber = date.getDate();
                const countPlaceElement = document.querySelector(`[data-day="${dayNumber}"] .count_place`);
                if (countPlaceElement) {
                    if (item.available_slots <= 0) {
                        countPlaceElement.closest('.wrap').classList.add('inactive');
                        countPlaceElement.closest('.wrap').removeAttribute('onclick');
                        countPlaceElement.closest('.wrap').style.cursor = 'default';
                    }
                    countPlaceElement.textContent = `${item.available_slots} місць`;
                }
            });
        });

}
async function getPrice(date) {
    try {
        const response = await fetch(`{% url 'site:get_price_day' %}?date=${date}`, {
            method: "GET",
            headers: {
                "X-Requested-With": "XMLHttpRequest",
            },
        });
        const data = await response.json();
        return data.price;
    } catch (error) {
        console.error('Помилка отримання ціни:', error);
        return null;
    }
}
</script>

vr_club_site/templates/site/game-carousel.html
{% load static %}
<link rel="stylesheet" href="{% static 'site/style/game-carousel.css' %}">
<section id="games" style="height: auto;">
    <div class="games">
        <span>
            <span class="span1">У </span>
            <span class="span2">що</span>
            <span class="span3"> пограти?</span>
        </span>
    </div>
    <div class="_15">Понад 15 крутих ігор як для компанії, так і для одного</div>
    <div class="wrapper">
        <ul class="carousel">
            <li class="card">
                <div class="game-card">
                    <div class="group-1">
                        <img class="game-image" src="{%  static 'site/static_files/Beat-Saver.png' %}" />
                        <div class="overlay"></div>
                        <div class="rectangle-12"></div>
                    </div>
                    <div class="game-title">Beat Saber</div>
                    <div class="age-badge">10+</div>
                    <div class="player-badge-two">Гравців: 1 - 2</div>
                    <div class="descriptions">
                        Beat saber so cool game
                    </div>
                    <button class="btn-blue" type="submit">Забронювати</button>
                    <div class="btn-play">
                        <div class="rectangle-32"></div>
                        <div class="rectangle-33"></div>
                        <svg class="ph-play-fill" width="18" height="18" viewBox="0 0 18 18" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M16.875 8.99998C16.8755 9.19097 16.8265 9.37883 16.7329 9.54529C16.6392 9.71174 16.5041 9.85114 16.3406 9.94991L6.21 16.1472C6.0392 16.2518 5.84358 16.3089 5.64334 16.3126C5.44309 16.3163 5.24549 16.2665 5.07094 16.1683C4.89805 16.0717 4.75402 15.9307 4.65368 15.7599C4.55333 15.5891 4.50029 15.3947 4.5 15.1966V2.80334C4.50029 2.60526 4.55333 2.41083 4.65368 2.24005C4.75402 2.06927 4.89805 1.92829 5.07094 1.83163C5.24549 1.73343 5.44309 1.68362 5.64334 1.68733C5.84358 1.69103 6.0392 1.74813 6.21 1.85272L16.3406 8.05006C16.5041 8.14883 16.6392 8.28822 16.7329 8.45468C16.8265 8.62114 16.8755 8.809 16.875 8.99998Z"
                                fill="#0E0E11"></path>
                        </svg>
                    </div>
                </div>
            </li>
            <li class="card">
                <div class="game-card">
                    <div class="group-1">
                        <img class="game-image" src="{% static 'site/static_files/Pavlov.png' %}" />
                        <div class="overlay"></div>
                        <div class="rectangle-12"></div>
                    </div>
                    <div class="game-title">Pavlov VR</div>
                    <div class="age-badge">16+</div>
                    <div class="player-badge-two">Гравців: 1 - 4</div>
                    <div class="descriptions">
                        Pavlov VR — багатокористувацький шутер у віртуальній реальності з великим
                        акцентом на функціях спільноти. Реалістичні функції перезавантаження та
                        швидкий бій як частина основного досвіду.
                    </div>
                    <button class="btn-blue" type="submit">Забронювати</button>
                    <div class="btn-play">
                        <div class="rectangle-32"></div>
                        <div class="rectangle-33"></div>
                        <svg class="ph-play-fill" width="18" height="18" viewBox="0 0 18 18" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M16.875 8.99998C16.8755 9.19097 16.8265 9.37883 16.7329 9.54529C16.6392 9.71174 16.5041 9.85114 16.3406 9.94991L6.21 16.1472C6.0392 16.2518 5.84358 16.3089 5.64334 16.3126C5.44309 16.3163 5.24549 16.2665 5.07094 16.1683C4.89805 16.0717 4.75402 15.9307 4.65368 15.7599C4.55333 15.5891 4.50029 15.3947 4.5 15.1966V2.80334C4.50029 2.60526 4.55333 2.41083 4.65368 2.24005C4.75402 2.06927 4.89805 1.92829 5.07094 1.83163C5.24549 1.73343 5.44309 1.68362 5.64334 1.68733C5.84358 1.69103 6.0392 1.74813 6.21 1.85272L16.3406 8.05006C16.5041 8.14883 16.6392 8.28822 16.7329 8.45468C16.8265 8.62114 16.8755 8.809 16.875 8.99998Z"
                                fill="#0E0E11"></path>
                        </svg>
                    </div>
                </div>
            </li>
            <li class="card">
                <div class="game-card">
                    <div class="group-1">
                        <img class="game-image" src="{% static 'site/static_files/Arizona.png' %}" />
                        <div class="overlay"></div>
                        <div class="rectangle-12"></div>
                    </div>
                    <div class="game-title">Arizona Sunshine</div>
                    <div class="age-badge">13+</div>
                    <div class="player-badge-two">Гравців: 1 - 4</div>
                    <div class="descriptions">
                        Arizona Sunshine cool game
                    </div>
                    <button class="btn-blue" type="submit">Забронювати</button>
                    <div class="btn-play">
                        <div class="rectangle-32"></div>
                        <div class="rectangle-33"></div>
                        <svg class="ph-play-fill" width="18" height="18" viewBox="0 0 18 18" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M16.875 8.99998C16.8755 9.19097 16.8265 9.37883 16.7329 9.54529C16.6392 9.71174 16.5041 9.85114 16.3406 9.94991L6.21 16.1472C6.0392 16.2518 5.84358 16.3089 5.64334 16.3126C5.44309 16.3163 5.24549 16.2665 5.07094 16.1683C4.89805 16.0717 4.75402 15.9307 4.65368 15.7599C4.55333 15.5891 4.50029 15.3947 4.5 15.1966V2.80334C4.50029 2.60526 4.55333 2.41083 4.65368 2.24005C4.75402 2.06927 4.89805 1.92829 5.07094 1.83163C5.24549 1.73343 5.44309 1.68362 5.64334 1.68733C5.84358 1.69103 6.0392 1.74813 6.21 1.85272L16.3406 8.05006C16.5041 8.14883 16.6392 8.28822 16.7329 8.45468C16.8265 8.62114 16.8755 8.809 16.875 8.99998Z"
                                fill="#0E0E11"></path>
                        </svg>
                    </div>
                </div>
            </li>
            <li class="card">
                <div class="game-card">
                    <div class="group-1">
                        <img class="game-image" src="{% static 'site/static_files/Fruit-Ninja.png' %}" />
                        <div class="overlay"></div>
                        <div class="rectangle-12"></div>
                    </div>
                    <div class="game-title">Fruit Ninja VR</div>
                    <div class="age-badge">12+</div>
                    <div class="player-badge-one">Гравців: 1</div>
                    <div class="descriptions">
                        Fruit Ninja VR cool game
                    </div>
                    <button class="btn-blue" type="submit">Забронювати</button>
                    <div class="btn-play">
                        <div class="rectangle-32"></div>
                        <div class="rectangle-33"></div>
                        <svg class="ph-play-fill" width="18" height="18" viewBox="0 0 18 18" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M16.875 8.99998C16.8755 9.19097 16.8265 9.37883 16.7329 9.54529C16.6392 9.71174 16.5041 9.85114 16.3406 9.94991L6.21 16.1472C6.0392 16.2518 5.84358 16.3089 5.64334 16.3126C5.44309 16.3163 5.24549 16.2665 5.07094 16.1683C4.89805 16.0717 4.75402 15.9307 4.65368 15.7599C4.55333 15.5891 4.50029 15.3947 4.5 15.1966V2.80334C4.50029 2.60526 4.55333 2.41083 4.65368 2.24005C4.75402 2.06927 4.89805 1.92829 5.07094 1.83163C5.24549 1.73343 5.44309 1.68362 5.64334 1.68733C5.84358 1.69103 6.0392 1.74813 6.21 1.85272L16.3406 8.05006C16.5041 8.14883 16.6392 8.28822 16.7329 8.45468C16.8265 8.62114 16.8755 8.809 16.875 8.99998Z"
                                fill="#0E0E11"></path>
                        </svg>
                    </div>
                </div>
            </li>
            <li class="card">
                <div class="game-card">
                    <div class="group-1">
                        <img class="game-image" src="{% static 'site/static_files/Job-Simulator.png' %}" />
                        <div class="overlay"></div>
                        <div class="rectangle-12"></div>
                    </div>
                    <div class="game-title">Job Simulator</div>
                    <div class="age-badge">12+</div>
                    <div class="player-badge-one">Гравців: 1</div>
                    <div class="descriptions">
                        Job simulator cool game
                    </div>
                    <button class="btn-blue" type="submit">Забронювати</button>
                    <div class="btn-play">
                        <div class="rectangle-32"></div>
                        <div class="rectangle-33"></div>
                        <svg class="ph-play-fill" width="18" height="18" viewBox="0 0 18 18" fill="none"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M16.875 8.99998C16.8755 9.19097 16.8265 9.37883 16.7329 9.54529C16.6392 9.71174 16.5041 9.85114 16.3406 9.94991L6.21 16.1472C6.0392 16.2518 5.84358 16.3089 5.64334 16.3126C5.44309 16.3163 5.24549 16.2665 5.07094 16.1683C4.89805 16.0717 4.75402 15.9307 4.65368 15.7599C4.55333 15.5891 4.50029 15.3947 4.5 15.1966V2.80334C4.50029 2.60526 4.55333 2.41083 4.65368 2.24005C4.75402 2.06927 4.89805 1.92829 5.07094 1.83163C5.24549 1.73343 5.44309 1.68362 5.64334 1.68733C5.84358 1.69103 6.0392 1.74813 6.21 1.85272L16.3406 8.05006C16.5041 8.14883 16.6392 8.28822 16.7329 8.45468C16.8265 8.62114 16.8755 8.809 16.875 8.99998Z"
                                fill="#0E0E11"></path>
                        </svg>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="main-view-more">
        <a href="{% url 'site:games' %}" class="view-more">Переглянути більше</a>
    </div>
</section>
<script src="{% static 'site/js/game-carousel.js' %}"></script>